FROM alpine:latest
RUN apk update \
    && apk add php7 \
    && apk add composer \
    && apk add php7-xml \
    && apk add php7-dom \
    && apk add php7-mbstring \
    && apk add php7-xmlwriter \
    && apk add php7-tokenizer \
    && apk add php7-simplexml \
    && apk add php7-pdo_mysql \
    && apk add php7-pdo \
    && apk add php7-session \
